Change XP blocks to store experience instead of levels
bl4ckscor3/GlobalXP pull request #4
Opened 2017-11-07 18:56 UTC by CplPibald

Shift right-click stores all of player's exp
Right-click extracts exactly how much exp is needed to move player to the next level
Block overlay still shows number of levels.  WailaDataProvider shows fractional levels too
Increase version to 1.4

2017-11-07 21:55 UTC, bl4ckscor3 requested changes
1. Please adapt your changes to the programming style used in the rest of the mod:

  - Braces on new lines
  - No space between if/while and the parantheses
  - Empty line infront of a while loop
  - No braces around an if statement with one 
instruction
  - Variable declarations should be at the top of each method if possible

2. Please capitalize XP everywhere except for identifiers starting with `xp`.
3. Please write all comments lower cased without a space after the `//`
4. The comment on line 24 should be in line 22 and the one at the end of line 31 should be at the end of line 29 in `EventHandler.java`
5. Unnecessary blank lines in `EventHandler.java`: 25, 35
6. Unnecessary blank lines in `TileEntityXPBlock.java`: 41, 44
7. Please add correct JavaDoc to the two new methods in `TileEntityXPBlock.java`

2017-11-07 22:45 UTC, CplPibald commented
I don't mind if you want to make these style changes prior to merge.  Thank you.

2017-11-15 18:03 UTC, bl4ckscor3 commented
I'm not going to bother adjusting your code. If you're not going to adapt it, this pr will be inevitably deadlocked.

2018-01-18 20:41 UTC, merged

2018-01-18 20:41 UTC, bl4ckscor3 commented
Merged #5 which contained the requested changes.